name: Build, Publish and Release PyPI and Conda Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CONDA_PKG_PATH: /usr/share/miniconda/conda-bld/noarch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: azure_storage_env
        python-version: 3.12.3
        auto-activate-base: false
        channels: olcbioinformatics,bioconda,conda-forge
    - name: Install Conda build
      run: conda install -y conda-build
    - name: Install conda-verify
      run: conda install -y conda-verify
    - name: Set version
      run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - name: Download source code
      run: wget https://github.com/OLC-LOC-Bioinformatics/AzureStorage/archive/$VERSION.tar.gz
    - name: Update meta.yaml
      run: |
        sed -i "s/{{ version }}/${VERSION#v}/g" recipes/meta.yaml
        sed -i "s|https://github.com/OLC-LOC-Bioinformatics/AzureStorage/archive/{{ version }}.tar.gz|https://github.com/OLC-LOC-Bioinformatics/AzureStorage/archive/$VERSION.tar.gz|g" recipes/meta.yaml
        sed -i "s/{{ fn }}/azure_storage-${VERSION#v}.tar.gz/g" recipes/meta.yaml
    - name: Build Conda package
      run: |
        conda build .
    - name: Upload Conda package
      uses: actions/upload-artifact@v2
      with:
        name: azure_storage
        path: $CONDA_PKG_PATH/azure_storage-*.tar.bz2
    - name: Install anaconda-client
      run: |
        conda install -y anaconda-client
        echo "$(conda info --base)/bin" >> $GITHUB_PATH
    - name: Upload package to olcbioinformatics
      run: |
        anaconda -t ${{ secrets.OLCBIOINFORMATICS_ANACONDA_API_TOKEN }} upload -u olcbioinformatics $CONDA_PKG_PATH/azure_storage-*.tar.bz2
    - name: Upload package to adamkoziol
      run: |
        anaconda -t ${{ secrets.ADAMKOZIOL_ANACONDA_API_TOKEN }} upload -u adamkoziol $CONDA_PKG_PATH/azure_storage-*.tar.bz2
